name: womensafetyapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  csc_picker: ^0.2.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/assets/fighter.png
    - lib/assets/facebook.png
    - lib/assets/google.png
    - lib/assets/logo.png